<?php
namespace app\common\controller;
use app\open\middleware\CheckOpenLogin;
use app\BaseController;
use think\facade\Config;
use think\Validate;


class OpenBase extends BaseController
{
    // 模型
    protected $model;
    // 服务
    protected $service;
    // 用户ID
    protected $userId;
    // 登录信息
    protected $userInfo;

    //请求用户
    protected $client_id;
    // 中间件
    protected $middleware = [
        CheckOpenLogin::class,
        //FormTokenCheck::class
    ];

    /**
     * 初始化
     * @author PENGKING
     * @since 2020/11/14
     */
    protected function initialize()
    {
        //echo $this->client_id;
        parent::initialize(); // TODO: Change the autogenerated stub
       // $token = request()->header("ClientId");
        $this->client_id = request()->header("ClientId");
        
    }

    /**
     * 数据格式核验
     * @author PENGKING
     * @since 2020-04-21
     * @param array $params 数据
     * @param array $rule 数据表名称
     * @param array $message 数据表名称
     */
    public  function  api_validate(array $params,array $rule,array $message)
    {
        //数据验证
        $validate = new Validate;
        $validate->rule($rule);
        $validate->message($message);
        if (!$validate->check($params)) {
            base_msg($validate->getError());
        }
    }



}