namespace app\admin\model;

use think\facade\Db;
/**
* <?php
echo $moduleTitle ?>-模型
* @author <?php echo $author ?>

* @since: <?php echo $since ?>

* Class <?php echo $moduleName ?>

* @package app\admin\model
*/
class <?php echo $moduleName ?> extends BaseModel
{
// 设置数据表名
protected $name = "<?php echo $tableName ?>";

/**
* 获取缓存信息
* @param int $id 记录ID
* @return \app\common\model\数据信息|mixed
* @throws \think\db\exception\DataNotFoundException
* @throws \think\db\exception\ModelNotFoundException
* @author <?php echo $author ?>

* @since: <?php echo $since ?>

*/
public function getInfo($id)
{
$info = parent::getInfo($id); // TODO: Change the autogenerated stub
if ($info) {
<?php if ($columnList) { ?>
    <?php foreach ($columnList as $val) { ?>
        <?php if (isset($val['columnImage']) && $val['columnImage']) { ?>
            $info['<?php echo $val['columnName'] ?>'] = get_image_url($info['<?php echo $val['columnName'] ?>']);
        <?php } ?>
        <?php if (isset($val['columnRow']) && $val['columnRow']) { ?>
            $info['<?php echo $val['columnName'] ?>'] = htmlspecialchars_decode($info['<?php echo $val['columnName'] ?>']);
        <?php } ?>

        <?php if (stripos($val['columnName'], "_guid") !== false) { ?>
            $table = '<?php echo str_replace('_guid', '', $val['columnName']); ?>';
            <?php if (str_replace('_guid', '', $val['columnName']) == 'uu') { ?>
                $info[$table] = Db::name('tq_user')->where('guid', $info['<?php echo $val['columnName']; ?>'])->where('mark', 1)->find();
            <?php } else { ?>
                $info[$table] = Db::name($table)->where('guid', $info['<?php echo $val['columnName']; ?>'])->where('mark', 1)->find();
            <?php } ?>
        <?php } ?>
    <?php } ?>
<?php } ?>

}
return $info;
}
}