<?php namespace app\admin\model;

use think\facade\Db;
/**
* 活动-模型
* @author PENGKING
* @since: 2022/10/09
* Class Activity
* @package app\admin\model
*/
class Activity extends BaseModel
{
// 设置数据表名
protected $name = "activity";

/**
* 获取缓存信息
* @param int $id 记录ID
* @return \app\common\model\数据信息|mixed
* @throws \think\db\exception\DataNotFoundException
* @throws \think\db\exception\ModelNotFoundException
* @author PENGKING
* @since: 2022/10/09
*/
public function getInfo($id)
{
$info = parent::getInfo($id); // TODO: Change the autogenerated stub
if ($info) {
                    
                            
                    $table = 'user';
                            $info[$table] = Db::name($table)->where('guid', $info['guid'])->where('mark', 1)->find();
                                        
                            
                                $info['cover_imgs'] = get_image_url($info['cover_imgs']);
                
                            
                            
                            
                            
                            
                            
                            
                            
                            
                            
                            
                            
                            
                            
                            
                            
                            
                            
                            
                            
                            
                            
                            
                            
                            
                            
                            
                            
                            
                            
                            
                            
            
}
return $info;
}
}