<?php


namespace app\admin\model;

/**
 * 广告位-模型
 * @author PENGKING
 * @since 2020/11/15
 * Class AdSort
 * @package app\admin\model
 */
class AdSort extends BaseModel
{
    // 设置数据表名
    protected $name = "ad_sort";

    /**
     * 获取记录信息
     * @param int $id 广告位ID
     * @return 数据信息|mixed
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @author PENGKING
     * @since 2020/11/15
     */
    public function getInfo($id)
    {
        $info = parent::getInfo($id); // TODO: Change the autogenerated stub
        if ($info) {
            // 获取栏目名称
            if ($info['cate_id']) {
                $itemCateModel = new ItemCate();
                $itemCateName = $itemCateModel->getCateName($info['cate_id'], ">>");
                $info['cate_name'] = $itemCateName;
            }
        }
        return $info;
    }

}