<?php 


namespace app\admin\model;


/**
 * 演示案例一-模型
 * @author PENGKING
 * @since: 2022/05/31
 * Class Example
 * @package app\admin\model
 */
class Example extends BaseModel
{
    // 设置数据表名
    protected $name = "example";

    /**
     * 获取缓存信息
     * @param int $id 记录ID
     * @return \app\common\model\数据信息|mixed
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @author PENGKING
     * @since: 2022/05/31
     */
    public function getInfo($id)
    {
        $info = parent::getInfo($id); // TODO: Change the autogenerated stub
        if ($info) {
                                                    
            // 头像
            $info['avatar'] = get_image_url($info['avatar']);
                                                                                                                                        
        }
        return $info;
    }
}