<?php 


namespace app\admin\model;


/**
 * 开放平台授权-模型
 * @author PENGKING
 * @since: 2022/07/14
 * Class OauthClient
 * @package app\admin\model
 */
class OauthClient extends BaseModel
{
    // 设置数据表名
    protected $name = "oauth_client";

    /**
     * 获取缓存信息
     * @param int $id 记录ID
     * @return \app\common\model\数据信息|mixed
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @author PENGKING
     * @since: 2022/07/14
     */
    public function getInfo($id)
    {
        $info = parent::getInfo($id); // TODO: Change the autogenerated stub
        if ($info) {
                                                                                                
        }
        return $info;
    }
}