<?php namespace app\admin\model;

use think\facade\Db;
/**
* 用户关注-模型
* @author PENGKING
* @since: 2022/10/08
* Class UserAttention
* @package app\admin\model
*/
class UserAttention extends BaseModel
{
// 设置数据表名
protected $name = "user_attention";

/**
* 获取缓存信息
* @param int $id 记录ID
* @return \app\common\model\数据信息|mixed
* @throws \think\db\exception\DataNotFoundException
* @throws \think\db\exception\ModelNotFoundException
* @author PENGKING
* @since: 2022/10/08
*/
public function getInfo($id)
{
$info = parent::getInfo($id); // TODO: Change the autogenerated stub
if ($info) {
                    
                            
                    $table = 'from';
                            $info[$table] = Db::name($table)->where('guid', $info['from_guid'])->where('mark', 1)->find();
                                        
                    $table = 'to';
                            $info[$table] = Db::name($table)->where('guid', $info['to_guid'])->where('mark', 1)->find();
                                        
                            
                            
            
}
return $info;
}
}