<?php namespace app\admin\model;

use think\facade\Db;
/**
* 人员测试-模型
* @author PENGKING
* @since: 2022/10/08
* Class UserTest
* @package app\admin\model
*/
class UserTest extends BaseModel
{
// 设置数据表名
protected $name = "user_test";

/**
* 获取缓存信息
* @param int $id 记录ID
* @return \app\common\model\数据信息|mixed
* @throws \think\db\exception\DataNotFoundException
* @throws \think\db\exception\ModelNotFoundException
* @author PENGKING
* @since: 2022/10/08
*/
public function getInfo($id)
{
$info = parent::getInfo($id); // TODO: Change the autogenerated stub
if ($info) {
                    
                            
            
}
return $info;
}
}