<?php


namespace app\admin\model;

/**
 * 网站专题-模型
 * @author PENGKING
 * @since 2021/7/6
 * Class WebsiteProject
 * @package app\admin\model
 */
class WebProject extends BaseModel
{
    // 设置数据表名称
    protected $name = "project_website";

    /**
     * 获取记录信息
     * @param int $id 记录ID
     * @return 数据信息|mixed
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @author PENGKING
     * @since 2021/7/6
     */
    public function getInfo($id)
    {
        $info = parent::getInfo($id); // TODO: Change the autogenerated stub
        if ($info) {
            // 文章封面
            if ($info['cover']) {
                $info['cover'] = get_image_url($info['cover']);
            }

            // 文章图集
            $users = [];
            if (isset($info['imgs']) && $info['imgs']) {
                $imgsList = unserialize($info['imgs']);
                foreach ($imgsList as $key => &$val) {
                    $val = get_image_url($val);
                    $users[] = [
                        'name' => "用户" . ($key + 1),
                        'avatar' => $val,
                    ];
                }
                $info['imgs'] = $imgsList;
            }
            $info['users'] = $users;

            // 发布时间
            if ($info['create_time']) {
                $info['time'] = get_format_time($info['create_time']);
            }
        }
        return $info;
    }

}