<?php namespace app\admin\model;

use think\facade\Db;
/**
* 小程序用户-模型
* @author PENGKING
* @since: 2022/10/08
* Class WxUser
* @package app\admin\model
*/
class WxUser extends BaseModel
{
// 设置数据表名
protected $name = "wx_user";

/**
* 获取缓存信息
* @param int $id 记录ID
* @return \app\common\model\数据信息|mixed
* @throws \think\db\exception\DataNotFoundException
* @throws \think\db\exception\ModelNotFoundException
* @author PENGKING
* @since: 2022/10/08
*/
public function getInfo($id)
{
$info = parent::getInfo($id); // TODO: Change the autogenerated stub
if ($info) {
                    
                            
                    $table = 'user';
                            $info[$table] = Db::name($table)->where('guid', $info['user_guid'])->where('mark', 1)->find();
                                        
                            
                            
                                $info['avatar'] = get_image_url($info['avatar']);
                
                            
                            
                            
                            
                            
                            
                            
                            
                            
                            
                            
            
}
return $info;
}
}