<?php namespace app\admin\model;

use think\facade\Db;

/**
 * 小程序用户-模型
 * @author PENGKING
 * @since: 2022/10/09
 * Class WxUser
 * @package app\admin\model
 */
class WxUser extends BaseModel
{
// 设置数据表名
    protected $name = "wx_user";

    /**
     * 获取缓存信息
     * @param int $id 记录ID
     * @return \app\common\model\数据信息|mixed
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @author PENGKING
     * @since: 2022/10/09
     */
    public function getInfo($id)
    {
        $info = parent::getInfo($id); // TODO: Change the autogenerated stub
        if (!empty($info)) {
            $wxInfo = new WxUserInfo();
            $userinfo = $wxInfo::where('guid', $info['guid'])->find()->toArray();
            if (!empty($userinfo)) {
                foreach ($userinfo as $field => $v) {
                    if (!isset($info[$field])) $info[$field] = $v;
                }
            }
            $info['gender'] = $info['gender'] == 1?'男':($info['gender'] == 2?'女':'');
        }
        return $info;
    }


}