<?php 


namespace app\admin\controller;


use app\admin\service\ActivityService;

/**
* 活动管理-控制器
* @author PENGKING
* @since: 2022/10/09
* Class Activity
* @package app\admin\controller
*/
class Activity extends Backend
{
/**
* 初始化方法
* @author PENGKING
* @since: 2022/10/09
*/
public function initialize()
{
parent::initialize(); // TODO: Change the autogenerated stub
$this->service = new ActivityService();
}

                                                                                                                                                                                                                                                                                                
                /**
                * 设置是否分队 10
                * @return mixed
                * @since 2022/10/09
                * @author PENGKING
                */
                public function setIsTeamPart()
                {
                if (IS_POST) {
                $result = $this->service->setIsTeamPart();
                return $result;
                }
                }
                                                                                                                                                                                                
/**
* 获取数据列表
* @return array
* @since 2022/10/09
* @author PENGKING

*/
public function getListSelect()
{
$result = $this->service->getListSelect();
return $result;
}




}