<?php


namespace app\admin\controller;


use app\admin\service\ActivityService;

/**
 * 活动管理-控制器
 * @author PENGKING
 * @since: 2022/10/13
 * Class Activity
 * @package app\admin\controller
 */
class Activity extends Backend
{
    /**
     * 初始化方法
     * @author PENGKING
     * @since: 2022/10/13
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new ActivityService();
    }


    /**
     * 获取数据列表
     * @return array
     * @since 2022/10/13
     * @author PENGKING
     */
    public function getListSelect()
    {
        $result = $this->service->getListSelect();
        return $result;
    }


}