<?php


namespace app\admin\controller;

use app\admin\service\ActionLogService;

/**
 * 行为日志-控制器
 * @author PENGKING
 * @since 2020/11/15
 * Class Actionlog
 * @package app\admin\controller
 */
class Actionlog extends Backend
{
    /**
     * 构造函数
     * @author PENGKING
     * @since 2020/11/15
     */
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new ActionLogService();
    }
}