<?php 


namespace app\admin\controller;


use app\admin\service\AdService;

/**
* 广告管理-控制器
* @author PENGKING
* @since: 2022/10/12
* Class Ad
* @package app\admin\controller
*/
class Ad extends Backend
{
/**
* 初始化方法
* @author PENGKING
* @since: 2022/10/12
*/
public function initialize()
{
parent::initialize(); // TODO: Change the autogenerated stub
$this->service = new AdService();
}

                                                                                                                                                                                                                                                                        
/**
* 获取数据列表
* @return array
* @since 2022/10/12
* @author PENGKING

*/
public function getListSelect()
{
$result = $this->service->getListSelect();
return $result;
}




}