<?php


namespace app\admin\controller;

use app\admin\service\AdSortService;

/**
 * 广告位-控制器
 * @author PENGKING
 * @since 2020/11/15
 * Class Adsort
 * @package app\admin\controller
 */
class Adsort extends Backend
{
    /**
     * 初始化
     * @author PENGKING
     * @since 2020/11/15
     */
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new AdSortService();
    }

    /**
     * 获取广告位列表
     * @return mixed
     * @since 2020/11/15
     * @author PENGKING
     */
    public function getAdSortList()
    {
        $result = $this->service->getAdSortList();
        return $result;
    }

}