<?php


namespace app\admin\controller;

use app\admin\service\ArticleService;

/**
 * 文章管理-控制器
 * @author PENGKING
 * @since 2021/6/4
 * Class Article
 * @package app\admin\controller
 */
class Article extends Backend
{
    /**
     * 初始化
     * @author PENGKING
     * @since 2021/6/4
     */
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new ArticleService();
    }
}