<?php


namespace app\admin\controller;

use app\admin\service\CityService;

/**
 * 城市管理-控制器
 * @author PENGKING
 * @since 2020/11/15
 * Class City
 * @package app\admin\controller
 */
class City extends Backend
{
    /**
     * 初始化
     * @author PENGKING
     * @since 2020/11/15
     */
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new CityService();
    }
}