<?php


namespace app\admin\controller;

use app\admin\service\ConfigService;

/**
 * 配置-控制器
 * @author PENGKING
 * @since 2020/11/15
 * Class Configgroup
 * @package app\admin\controller
 */
class Config extends Backend
{
    /**
     * 初始化
     * @author PENGKING
     * @since 2020/11/15
     */
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new ConfigService();
    }
}