<?php


namespace app\admin\controller;

use app\admin\service\DeptService;

/**
 * 部门管理-控制器
 * @author PENGKING
 * @since 2020/11/15
 * Class Dept
 * @package app\admin\controller
 */
class Dept extends Backend
{
    /**
     * 初始化
     * @author PENGKING
     * @since 2020/11/15
     */
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new DeptService();
    }

    /**
     * 获取部门列表
     * @author PENGKING
     * @since 2021/5/26
     */
    public function getDeptList()
    {
        $result = $this->service->getDeptList();
        return $result;
    }
}