<?php


namespace app\admin\controller;

use app\admin\service\DictService;

/**
 * 字典-控制器
 * @author PENGKING
 * @since 2020/11/15
 * Class Dicttype
 * @package app\admin\controller
 */
class Dict extends Backend
{
    /**
     * 构造函数
     * @author PENGKING
     * @since 2020/11/15
     */
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new DictService();
    }

}