<?php 


namespace app\admin\controller;


use app\admin\service\ExampleService;

/**
 * 演示案例一管理-控制器
 * @author PENGKING
 * @since: 2022/05/31
 * Class Example
 * @package app\admin\controller
 */
class Example extends Backend
{
    /**
     * 初始化方法
     * @author PENGKING
     * @since: 2022/05/31
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new ExampleService();
    }
	
                            	        
	/**
	 * 设置是否VIP
	 * @return mixed
	 * @since 2022/05/31
	 * @author PENGKING	 
	 */
	public function setIsVip()
	{
		if (IS_POST) {
			$result = $this->service->setIsVip();
			return $result;
		}
	}
    	                            
        /**
        * 获取数据列表
        * @return array
        * @since 2022/05/31
        * @author PENGKING

        */
        public function getListSelect()
        {
            $result = $this->service->getListSelect();
            return $result;
        }

}