<?php 


namespace app\admin\controller;


use app\admin\service\Example2Service;

/**
 * 演示案例二管理-控制器
 * @author PENGKING
 * @since: 2021/12/17
 * Class Example2
 * @package app\admin\controller
 */
class Example2 extends Backend
{
    /**
     * 初始化方法
     * @author PENGKING
     * @since: 2021/12/17
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new Example2Service();
    }
	
                    	                            
}