<?php


namespace app\admin\controller;

use app\admin\service\FileService;
use think\facade\Filesystem;

/**
 * 文件管理-控制器
 * @author PENGKING
 * @since 2021/7/10
 * Class File
 * @package app\admin\controller
 */
class File extends Backend
{
    /**
     * 初始化
     * @author PENGKING
     * @since 2021/7/10
     */
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->model = new \app\admin\model\File();
        $this->service = new FileService();
    }

    /**
     * 创建文件夹
     * @return mixed
     * @since 2021/7/10
     * @author PENGKING
     */
    public function saveDir()
    {
        $result = $this->service->saveDir();
        return $result;
    }

    /**
     * 上传文件
     * @return mixed
     * @since 2021/7/10
     * @author PENGKING
     */
    public function uploadFile()
    {
        // 参数
        $param = request()->param();
        // 目录文件夹名称
        $directoryId = isset($param['directoryId']) ? $param['directoryId'] : 0;

        // 获取文件对象
        $file = \request()->file('file');
        $savename = Filesystem::putFile('file', $file);
        if (!$savename) {
            return message("文件上传失败", false);
        }
        // 拼接路径
        $path = str_replace('\\', '/', '/' . $savename);

        $isImage = 2;
        if (strpos($_FILES['file']['type'], "image") !== false) {
            $isImage = 1;
        }
        // 存储
        $data = [
            'name' => $file->getOriginalName(),
            'pid' => $directoryId,
            'length' => $file->getSize(),
            'url' => $path,
            'thumbnail' => $path,
            'directory' => 1,
            'type' => $isImage,
        ];
        $res = $this->model->edit($data);
        if (!$res) {
            return message("文件保存失败", false);
        }
        return message("上传成功", true);
    }

}