<?php


namespace app\admin\controller;

use app\admin\service\MenuService;
use app\admin\service\UserService;

/**
 * 系统主页-控制器
 * @author PENGKING
 * @since 2020/11/14
 * Class Index
 * @package app\admin\controller
 */
class Index extends Backend
{

    /**
     * 初始化
     * @return array|void
     * @since 2021/1/8
     * @author PENGKING
     */
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

    }

    /**
     * 获取菜单列表
     * @author PENGKING
     * @since 2020/11/14
     */
    public function getMenuList()
    {
        $menuService = new MenuService();
        $result = $menuService->getPermissionList($this->userId);
        return $result;
    }

    /**
     * 获取用户信息
     * @return array
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @since 2020/11/20
     * @author PENGKING
     */
    public function getUserInfo()
    {
        $userService = new UserService();
        $result = $userService->getUserInfo($this->userId);
        return $result;
    }

    /**
     * 更新个人资料
     * @return mixed
     * @since 2020/11/11
     * @author PENGKING
     */
    public function updateUserInfo()
    {
        $userService = new UserService();
        $result = $userService->updateUserInfo($this->userId);
        return $result;
    }

    /**
     * 更新密码
     * @return array
     * @throws \think\db\exception\BindParamException
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @author PENGKING
     * @since 2020/11/15
     */
    public function updatePwd()
    {
        $userService = new UserService();
        $result = $userService->updatePwd($this->userId);
        return $result;
    }

}