<?php


namespace app\admin\controller;

use app\admin\service\ItemService;

/**
 * 站点管理-控制器
 * @author PENGKING
 * @since 2020/11/15
 * Class Item
 * @package app\admin\controller
 */
class Item extends Backend
{
    /**
     * 初始化
     * @author PENGKING
     * @since 2020/11/15
     */
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new ItemService();
    }

    /**
     * 获取站点列表
     * @return mixed
     * @since 2020/11/15
     * @author PENGKING
     */
    public function getItemList()
    {
        $result = $this->service->getItemList();
        return $result;
    }

}