<?php


namespace app\admin\controller;

use app\admin\service\ItemCateService;

/**
 * 栏目管理-控制器
 * @author PENGKING
 * @since 2020/11/15
 * Class Itemcate
 * @package app\admin\controller
 */
class Itemcate extends Backend
{
    /**
     * 初始化
     * @author PENGKING
     * @since 2020/11/15
     */
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new ItemCateService();
    }

    /**
     * 获取栏目列表
     * @return mixed
     * @since 2021/9/20
     * @author PENGKING
     */
    public function getCateList()
    {
        $result = $this->service->getCateList();
        return $result;
    }

}