<?php


namespace app\admin\controller;

use app\admin\service\LayoutDescService;

/**
 * 布局描述-控制器
 * @author PENGKING
 * @since 2020/11/15
 * Class Layoutdesc
 * @package app\admin\controller
 */
class Layoutdesc extends Backend
{
    /**
     * 初始化
     * @author PENGKING
     * @since 2020/11/15
     */
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new LayoutDescService();
    }

    /**
     * 获取布局描述列表
     */
    public function getLayoutDescList()
    {
        $result = $this->service->getLayoutDescList();
        return $result;
    }

}