<?php


namespace app\admin\controller;

use app\admin\service\LevelService;
/**
 * 职级管理-控制器
 * @author PENGKING
 * @since 2020/11/14
 * Class Level
 * @package app\admin\controller
 */
class Level extends Backend
{
    /**
     * 构造函数
     * @author PENGKING
     * @since 2020/11/14
     */
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->model = new \app\admin\model\Level();
        $this->service = new LevelService();
    }

    /**
     * 获取职级列表
     * @return mixed
     * @since 2020/11/14
     * @author PENGKING
     */
    public function getLevelList()
    {
        $result = $this->service->getLevelList();
        return $result;
    }

    public function exportExcel(){
        // 参数
        $param = request()->param();
        // 查询条件
        $where = [];
        // 职级名称
        $name = isset($param['name']) ? $param['name'] : "";
        if ($name) {
            $where[] = ["name", "like", "%{$name}%"];
        }
        $where[] = ['mark', "=", 1];
        // 获取导出的数据源
        $list = $this->model->where($where)->field('id,name,status,sort')->select()->toArray();
        $excel = new \Excel();
        $headArr =array('职级ID','职级名称','职级状态','排序');
        $data = $excel->excel_export("职级信息", $headArr, $list, $fileName = '职级');
        return message("操作成功", true, $data);
    }

    /**
     * 导入Excel
     * @author PENGKING
     * @since 2021/5/24
     */
    public function importExcel()
    {
        $files = request()->file('file');
        $excel = new \Excel();
        $data = $excel->import_excel($files,"level");
        foreach ($data as $value){
            $dataArr = array();
            $dataArr['name'] = $value[0];
            // 状态
            $dataArr['status'] = $value[1] == "正常" ? 1 : 2;
            // 排序
            $dataArr['sort'] =  $value[2];
            $levemModel = new \app\admin\model\Level();
            $levemModel->edit($dataArr);
        }
        return  ok_msg("本次共导入". count($data)."条数据");

    }


}