<?php


namespace app\admin\controller;

use app\admin\service\LoginService;
use think\facade\Db;

/**
 * 登录-控制器
 * @author PENGKING
 * @since 2020/11/14
 * Class Login
 * @package app\admin\controller
 */
class Login extends Backend
{
    /**
     * 初始化
     * @author PENGKING
     * @since 2020/11/14
     */
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new LoginService();
    }

    /**
     * 验证码
     * @return mixed
     * @since 2020/11/14
     * @author PENGKING
     */
    public function captcha()
    {
        $result = $this->service->captcha();
        return json($result);
    }

    /**
     * 登录
     * @return mixed
     * @since 2020/11/14
     * @author PENGKING
     */
    public function login()
    {
        $result = $this->service->login();
        return $result;
    }

    /**
     * 退出系统
     * @return mixed
     * @since 2020/11/14
     * @author PENGKING
     */
    public function logout()
    {
        $result = $this->service->logout();
        return $result;
    }

    /**
     * 获取系统配置
     * @return mixed
     * @since 2020/11/14
     * @author PENGKING
     */

    public function get_config_data()
    {
        $config_id = request()->param('config_id',1);
        $list = cache('sys_config_id'.$config_id);
        if(empty($list)) {
            $list = Db::name('config_data')
                ->where('config_id', $config_id)->cache('sys_config_id' . $config_id, 7200)
                ->column('code,value');
        }
        $data =[];
        if(!empty($list)){
            foreach ($list as $key=>$val){
                if($val['code'] =="login_img"||$val['code'] =="site_logo"){
                    $data[$key][$val['code']] = get_image_url($val['value']);
                }else{
                    $data[$key][$val['code']] = $val['value'];
                }

            }
            return ok_msg('成功',$data);
        }else{
            return err_msg('暂无数据');
        }

    }
}