<?php


namespace app\admin\controller;

use app\admin\service\MemberLevelService;

/**
 * 会员等级-控制器
 * @author PENGKING
 * @since 2020/11/15
 * Class Memberlevel
 * @package app\admin\controller
 */
class Memberlevel extends Backend
{
    /**
     * 初始化
     * @author PENGKING
     * @since 2020/11/15
     */
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new MemberLevelService();
    }

    /**
     * 获取会员等级列表
     * @return mixed
     * @since 2020/11/15
     * @author PENGKING
     */
    public function getMemberLevelList()
    {
        $result = $this->service->getMemberLevelList();
        return $result;
    }

}