<?php


namespace app\admin\controller;

use app\admin\service\NoticeService;

/**
 * 通知公告-控制器
 * @author PENGKING
 * @since 2020/11/15
 * Class Notice
 * @package app\admin\controller
 */
class Notice extends Backend
{
    /**
     * 初始化
     * @author PENGKING
     * @since 2020/11/15
     */
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new NoticeService();
    }

    /**
     * 设置置顶
     * @author PENGKING
     * @since 2020/11/21
     */
    public function setIsTop()
    {
        $result = $this->service->setIsTop();
        return $result;
    }

}