<?php 


namespace app\admin\controller;


use app\admin\service\OauthclientService;

/**
 * 开放平台授权管理-控制器
 * @author PENGKING
 * @since: 2022/07/14
 * Class Oauthclient
 * @package app\admin\controller
 */
class Oauthclient extends Backend
{
    /**
     * 初始化方法
     * @author PENGKING
     * @since: 2022/07/14
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new OauthclientService();
    }
	
                            
        /**
        * 获取数据列表
        * @return array
        * @since 2022/07/14
        * @author PENGKING

        */
        public function getListSelect()
        {
            $result = $this->service->getListSelect();
            return $result;
        }

}