<?php 


namespace app\admin\controller;


use app\admin\service\Openlog202203Service;

/**
 * 系统行为日志管理-控制器
 * @author PENGKING
 * @since: 2022/03/29
 * Class Openlog202203
 * @package app\admin\controller
 */
class Openlog202203 extends Backend
{
    /**
     * 初始化方法
     * @author PENGKING
     * @since: 2022/03/29
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new Openlog202203Service();
    }
	
                                                
}