<?php


namespace app\admin\controller;

use app\admin\service\OrganizationService;

/**
 * 组织机构-控制器
 * @author PENGKING
 * @since 2021/7/5
 * Class Organization
 * @package app\admin\controller
 */
class Organization extends Backend
{
    /**
     * 初始化
     * @author PENGKING
     * @since 2021/7/5
     */
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new OrganizationService();
    }
}