<?php


namespace app\admin\controller;

use app\admin\service\PositionService;

/**
 * 岗位管理-控制器
 * @author PENGKING
 * @since 2020/11/14
 * Class Position
 * @package app\admin\controller
 */
class Position extends Backend
{
    /**
     * 初始化
     * @author PENGKING
     * @since 2020/11/14
     */
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new PositionService();
    }

    /**
     * 获取岗位列表
     * @return mixed
     * @since 2020/11/14
     * @author PENGKING
     */
    public function getPositionList()
    {
        $result = $this->service->getPositionList();
        return $result;
    }

}