<?php 


namespace app\admin\controller;


use app\admin\service\Test6Service;

/**
 * 关联5管理-控制器
 * @author PENGKING
 * @since: 2022/07/27
 * Class Test6
 * @package app\admin\controller
 */
class Test6 extends Backend
{
    /**
     * 初始化方法
     * @author PENGKING
     * @since: 2022/07/27
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new Test6Service();
    }
	
                                            
        /**
        * 获取数据列表
        * @return array
        * @since 2022/07/27
        * @author PENGKING

        */
        public function getListSelect()
        {
            $result = $this->service->getListSelect();
            return $result;
        }

}