<?php 


namespace app\admin\controller;


use app\admin\service\Test1Service;

/**
 * Test1管理-控制器
 * @author PENGKING
 * @since: 2022/07/21
 * Class Test1
 * @package app\admin\controller
 */
class Test1 extends Backend
{
    /**
     * 初始化方法
     * @author PENGKING
     * @since: 2022/07/21
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new Test1Service();
    }
	
                                            
        /**
        * 获取数据列表
        * @return array
        * @since 2022/07/21
        * @author PENGKING

        */
        public function getListSelect()
        {
            $result = $this->service->getListSelect();
            return $result;
        }

}