<?php 


namespace app\admin\controller;


use app\admin\service\Test2Service;

/**
 * Test2管理-控制器
 * @author PENGKING
 * @since: 2022/07/22
 * Class Test2
 * @package app\admin\controller
 */
class Test2 extends Backend
{
    /**
     * 初始化方法
     * @author PENGKING
     * @since: 2022/07/22
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new Test2Service();
    }
	
                                                    
        /**
        * 获取数据列表
        * @return array
        * @since 2022/07/22
        * @author PENGKING

        */
        public function getListSelect()
        {
            $result = $this->service->getListSelect();
            return $result;
        }

}