<?php 


namespace app\admin\controller;


use app\admin\service\TquserService;

/**
 * 腾青用户管理-控制器
 * @author PENGKING
 * @since: 2022/05/31
 * Class Tquser
 * @package app\admin\controller
 */
class Tquser extends Backend
{
    /**
     * 初始化方法
     * @author PENGKING
     * @since: 2022/05/31
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new TquserService();
    }
	
                                                            	                                                                        
        /**
        * 获取数据列表
        * @return array
        * @since 2022/05/31
        * @author PENGKING

        */
        public function getListSelect()
        {
            $result = $this->service->getListSelect();
            return $result;
        }

}