<?php 


namespace app\admin\controller;


use app\admin\service\UsertestService;

/**
* 人员测试管理-控制器
* @author PENGKING
* @since: 2022/10/08
* Class Usertest
* @package app\admin\controller
*/
class Usertest extends Backend
{
/**
* 初始化方法
* @author PENGKING
* @since: 2022/10/08
*/
public function initialize()
{
parent::initialize(); // TODO: Change the autogenerated stub
$this->service = new UsertestService();
}

                            
/**
* 获取数据列表
* @return array
* @since 2022/10/08
* @author PENGKING

*/
public function getListSelect()
{
$result = $this->service->getListSelect();
return $result;
}




}