<?php 


namespace app\admin\controller;


use app\admin\service\UserdynamicthumbService;

/**
* 用户动态点赞管理-控制器
* @author PENGKING
* @since: 2022/10/08
* Class Userdynamicthumb
* @package app\admin\controller
*/
class Userdynamicthumb extends Backend
{
/**
* 初始化方法
* @author PENGKING
* @since: 2022/10/08
*/
public function initialize()
{
parent::initialize(); // TODO: Change the autogenerated stub
$this->service = new UserdynamicthumbService();
}

                                                                                                            
/**
* 获取数据列表
* @return array
* @since 2022/10/08
* @author PENGKING

*/
public function getListSelect()
{
$result = $this->service->getListSelect();
return $result;
}




}