<?php 


namespace app\admin\controller;


use app\admin\service\VotelogService;

/**
 * 投票记录管理-控制器
 * @author PENGKING
 * @since: 2022/07/26
 * Class Votelog
 * @package app\admin\controller
 */
class Votelog extends Backend
{
    /**
     * 初始化方法
     * @author PENGKING
     * @since: 2022/07/26
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new VotelogService();
    }
	
                                            
        /**
        * 获取数据列表
        * @return array
        * @since 2022/07/26
        * @author PENGKING

        */
        public function getListSelect()
        {
            $result = $this->service->getListSelect();
            return $result;
        }

}