<?php 


namespace app\admin\controller;


use app\admin\service\VotingitemsService;

/**
 * 投票选项管理-控制器
 * @author PENGKING
 * @since: 2022/07/25
 * Class Votingitems
 * @package app\admin\controller
 */
class Votingitems extends Backend
{
    /**
     * 初始化方法
     * @author PENGKING
     * @since: 2022/07/25
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new VotingitemsService();
    }
	
                                                                            
        /**
        * 获取数据列表
        * @return array
        * @since 2022/07/25
        * @author PENGKING

        */
        public function getListSelect()
        {
            $result = $this->service->getListSelect();
            return $result;
        }

}