<?php


namespace app\admin\controller;

use app\admin\service\WebProjectService;

/**
 * 网站专题-控制器
 * @author PENGKING
 * @since 2021/7/6
 * Class Websiteproject
 * @package app\admin\controller
 */
class Webproject extends Backend
{
    /**
     * 初始化
     * @author PENGKING
     * @since 2021/7/6
     */
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new WebProjectService();
    }
}