<?php 


namespace app\admin\service;


use app\admin\model\ActionLog202112;

/**
 * 系统行为日志管理-服务类
 * @author PENGKING
 * @since: 2022/04/02
 * Class ActionLog202112Service
 * @package app\admin\service
 */
class ActionLog202112Service extends BaseService
{
    /**
     * 构造函数
     * LevelService constructor.
     */
    public function __construct()
    {
        $this->model = new ActionLog202112();
    }
	
	/**
     * 获取数据列表
     * @return array
     * @since 2022/04/02
     * @author PENGKING
     */
    public function getList()
    {
        $param = request()->param();

        // 查询条件
        $map = [];
		
	
	    // 日志标题
        $title = isset($param['title']) ? trim($param['title']) : '';
        if ($title) {
            $map[] = ['title', 'like', "%{$title}%"];
        }
		
	    // 操作类型
        $type = isset($param['type']) ? (int)$param['type'] : 0;
        if ($type) {
            $map[] = ['type', '=', $type];
        }
		
	    // 有效标识
        $mark = isset($param['mark']) ? (int)$param['mark'] : 0;
        if ($mark) {
            $map[] = ['mark', '=', $mark];
        }
	
        return parent::getList($map); // TODO: Change the autogenerated stub
    }


                                                                    
        /**
        * 获取数据列表
        * @return array
        * @since 2022/04/02        * @author PENGKING        */
        public function getListSelect()
        {
            return parent::getListSelect();
        }

}