<?php namespace app\admin\service;


use app\admin\model\Activity;
use app\admin\model\Advert;

/**
 * 广告管理-服务类
 * @author PENGKING
 * @since: 2022/10/14
 * Class AdvertService
 * @package app\admin\service
 */
class AdvertService extends BaseService
{
    /**
     * 构造函数
     * LevelService constructor.
     */
    public function __construct()
    {
        $this->model = new Advert();
    }

    /**
     * 获取数据列表
     * @return array
     * @since 2022/10/14
     * @author PENGKING
     */
    public function getList()
    {
        $param = request()->param();

// 查询条件
        $map = [];


        // 广告标题
        $title = isset($param['title']) ? trim($param['title']) : '';
        if ($title) {
            $map[] = ['title', 'like', "%{$title}%"];
        }

        // 广告位
        $pid = isset($param['pid']) ? (int)$param['pid'] : 0;
        if ($pid) {
            $map[] = ['pid', '=', $pid];
        }
        // 状态
        $status = isset($param['status']) ? (int)$param['status'] : 0;
        if ($status) {
            $map[] = ['status', '=', $status];
        }

        return parent::getList($map); // TODO: Change the autogenerated stub
    }

    /**
     * 添加或编辑
     * @return array
     * @since 2022/10/14
     * @author PENGKING
     */
    public function edit()
    {
        // 参数
        $data = request()->param();
        if (!empty($data['start_time']) && !empty($data['end_time']) && strtotime($data['start_time']) > strtotime($data['end_time'])) {
            base_msg('广告开始时间不可大于结束时间');
        }
        // 广告图片处理
        $image_url = getter($data, 'image_url');
        if (!empty($image_url)) {
            if (strpos($image_url, "temp") !== false) {
                $data['image_url'] = save_image($image_url, 'advert');
            } else {
                $data['image_url'] = str_replace(IMG_URL, "", $image_url);
            }
        }
        $data['sort'] = !empty($data['sort'])?$data['sort']:0;
        if (!empty($data['activity_sn'])) {
            $activityModel = new Activity();
            $info = $activityModel->getInfoBySn($data['activity_sn']);
            if (empty($info)) base_msg('关联活动不存在或已删除');
        }
        $data['start_time'] = !empty($data['start_time'])?$data['start_time']:['exp','null'];
        $data['end_time'] = !empty($data['end_time'])?$data['end_time']:['exp','null'];
//        print_r($data);exit;
        return parent::edit($data); // TODO: Change the autogenerated stub
    }


    /**
     * 获取数据列表
     * @return array
     * @since 2022/10/14* @author PENGKING
     */
    public function getListSelect()
    {
        return parent::getListSelect();
    }

}