<?php


namespace app\admin\service;

use app\admin\model\ConfigData;

/**
 * 配置数据-服务类
 * @author PENGKING
 * @since 2020/11/15
 * Class ConfigService
 * @package app\admin\service
 */
class ConfigDataService extends BaseService
{
    /**
     * 构造函数
     * @author PENGKING
     * @since 2020/11/15
     * ConfigService constructor.
     */
    public function __construct()
    {
        $this->model = new ConfigData();
    }

    /**
     * 获取数据列表
     * @return array
     * @since 2021/5/26
     * @author PENGKING
     */
    public function getList()
    {
        $param = request()->param();
        // 查询条件
        $map = [];
        // 配置ID
        $configId = getter($param, "configId", 0);
        if ($configId) {
            $map[] = ['config_id', '=', $configId];
        }
        // 字典名称
        $name = getter($param, "name");
        if ($name) {
            $map[] = ['name', 'like', "%{$name}%"];
        }
        // 字典编码
        $code = getter($param, 'code');
        if ($code) {
            $map[] = ['code', '=', $code];
        }
        return parent::getList($map, "sort asc"); // TODO: Change the autogenerated stub
    }

    /**
     * 添加或编辑
     * @return array
     * @since 2021/12/17
     * @author PENGKING
     */
    public function edit()
    {
        // 参数
        $data = request()->param();
        if (!$data) {
            return message("参数不能为空", false);
        }
        // 配置项类型
        $type = isset($data['type']) ? $data["type"] : "";
        if (empty($type)) {
            return message("配置类型不能为空", false);
        }
        // 配置项值
        $value = isset($data['value']) ? $data['value'] : "";
        // 单图处理
        if ($type == "image") {
            $preg = "/^http(s)?:\\/\\/.+/";
            if (is_string($value) && preg_match($preg, $value)) {
                if (strpos($value, "temp") !== false) {
                    $data['value'] = save_image($value, 'config');
                } else {
                    $data['value'] = str_replace(IMG_URL, "", $value);
                }
            }
        }
        // 多图处理
        if ($type == "images") {
            if (is_array($value)) {
                $item = [];
                foreach ($value as $vt) {
                    $preg = "/^http(s)?:\\/\\/.+/";
                    if (preg_match($preg, $vt)) {
                        if (strpos($vt, "temp") !== false) {
                            $vt = save_image($vt, 'config');
                        } else {
                            $vt = str_replace(IMG_URL, "", $vt);
                        }
                        $item[] = $vt;
                    } else {
                        $item[] = $vt;
                    }
                }
                $data['value'] = !empty($item) ? implode(",", $item) : "";
            }
        }
        return parent::edit($data); // TODO: Change the autogenerated stub
    }

}