<?php 


namespace app\admin\service;


use app\admin\model\Example;

/**
 * 演示案例一管理-服务类
 * @author PENGKING
 * @since: 2022/05/31
 * Class ExampleService
 * @package app\admin\service
 */
class ExampleService extends BaseService
{
    /**
     * 构造函数
     * LevelService constructor.
     */
    public function __construct()
    {
        $this->model = new Example();
    }
	
	/**
     * 获取数据列表
     * @return array
     * @since 2022/05/31
     * @author PENGKING
     */
    public function getList()
    {
        $param = request()->param();

        // 查询条件
        $map = [];
		
	
	    // 测试名称
        $name = isset($param['name']) ? trim($param['name']) : '';
        if ($name) {
            $map[] = ['name', 'like', "%{$name}%"];
        }
		
	    // 性别
        $gender = isset($param['gender']) ? (int)$param['gender'] : 0;
        if ($gender) {
            $map[] = ['gender', '=', $gender];
        }
		
	    // 类型
        $type = isset($param['type']) ? (int)$param['type'] : 0;
        if ($type) {
            $map[] = ['type', '=', $type];
        }
		
	    // 状态
        $status = isset($param['status']) ? (int)$param['status'] : 0;
        if ($status) {
            $map[] = ['status', '=', $status];
        }
		
	    // 是否VIP
        $is_vip = isset($param['is_vip']) ? (int)$param['is_vip'] : 0;
        if ($is_vip) {
            $map[] = ['is_vip', '=', $is_vip];
        }
	
        return parent::getList($map); // TODO: Change the autogenerated stub
    }

	/**
     * 添加或编辑
     * @return array
     * @since 2022/05/31
     * @author PENGKING
     */
    public function edit()
    {
        // 参数
        $data = request()->param();
	                                            
		// 头像处理
        $avatar = getter($data, 'avatar');
        if (!empty($avatar)) {
            if (strpos($avatar, "temp") !== false) {
                $data['avatar'] = save_image($avatar, 'example');
            } else {
                $data['avatar'] = str_replace(IMG_URL, "", $avatar);
            }
        }
                                                                                                                                    
        return parent::edit($data); // TODO: Change the autogenerated stub
    }

                        		    	
	/**
     * 设置是否VIP     
	 * @return array
     * @throws \think\db\exception\BindParamException
     * @throws \think\exception\PDOException
     * @since 2022/05/31     
	 * @author PENGKING     
	 */
    public function setIsVip()
    {
		// 参数
        $data = request()->param();
        $id = getter($data, "id", 0);
        if (!$id) {
            return message('记录ID不能为空', false);
        }
        $is_vip = getter($data, "is_vip", 0);
        if (!$is_vip) {
            return message('记录是否VIP不能为空', false);
        }
        $error = '';
        $item = [
            'id' => $id,
            'is_vip' => $is_vip        ];
        $rowId = $this->model->edit($item, $error);
        if (!$rowId) {
            return message($error, false);
        }
        return message();
    }
    	                            
        /**
        * 获取数据列表
        * @return array
        * @since 2022/05/31        * @author PENGKING        */
        public function getListSelect()
        {
            return parent::getListSelect();
        }

}