<?php


namespace app\admin\service;

use app\admin\model\ItemCate;

/**
 * 栏目管理-服务类
 * @author PENGKING
 * @since 2020/11/15
 * Class ItemCateService
 * @package app\admin\service
 */
class ItemCateService extends BaseService
{
    /**
     * 构造函数
     * @author PENGKING
     * @since 2020/11/15
     * ItemCateService constructor.
     */
    public function __construct()
    {
        $this->model = new ItemCate();
    }

    /**
     * 获取栏目列表
     * @return array
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @since 2020/11/15
     * @author PENGKING
     */
    public function getList()
    {
        $list = $this->model->getList([], "sort asc");
        return message("操作成功", true, $list);
    }

    /**
     * 添加或编辑
     * @return mixed
     * @since 2020/11/20
     * @author PENGKING
     */
    public function edit()
    {
        // 请求参数
        $data = request()->param();
        // 是否有封面
        $is_cover = getter($data, "is_cover");
        if ($is_cover == 1) {
            // 有封面
            $cover = getter($data, 'cover');
            if (!empty($cover)) {
                if (strpos($cover, "temp") !== false) {
                    $data['cover'] = save_image($cover, 'itemcate');
                } else {
                    $data['cover'] = str_replace(IMG_URL, "", $cover);
                }
            }
        } else {
            // 无封面
            $data['cover'] = "";
        }
        return parent::edit($data); // TODO: Change the autogenerated stub
    }

    /**
     * 获取栏目列表
     * @return array
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\DbException
     * @throws \think\db\exception\ModelNotFoundException
     * @author PENGKING
     * @since 2021/9/20
     */
    public function getCateList()
    {
        $list = $this->model->where([
            ['status', '=', 1],
            ['mark', '=', 1],
        ])->order("sort", "asc")
            ->select()
            ->toArray();
        return message("操作成功", true, $list);
    }

}