<?php


namespace app\admin\service;

use app\admin\model\Item;

/**
 * 站点管理-服务类
 * @author PENGKING
 * @since 2020/11/15
 * Class ItemService
 * @package app\admin\service
 */
class ItemService extends BaseService
{
    /**
     * 构造函数
     * @author PENGKING
     * @since 2020/11/15
     * ItemService constructor.
     */
    public function __construct()
    {
        $this->model = new Item();
    }

    /**
     * 获取站点列表
     * @return array
     * @since 2020/11/15
     * @author PENGKING
     */
    public function getList()
    {
        $param = request()->param();

        // 查询条件
        $map = [];
        // 站点类型
        $type = getter($param, "type", 0);
        if ($type) {
            $map[] = ["type", '=', $type];
        }
        return parent::getList($map); // TODO: Change the autogenerated stub
    }

    /**
     * 添加或编辑
     * @return array
     * @since 2020/11/15
     * @author PENGKING
     */
    public function edit()
    {
        // 请求参数
        $data = request()->param();

        // 图片处理
        $image = getter($data, "image");
        if (!empty($image)) {
            if (strpos($image, "temp") !== false) {
                $data['image'] = save_image($image, 'item');
            } else {
                $data['image'] = str_replace(IMG_URL, "", $image);
            }
        }
        return parent::edit($data); // TODO: Change the autogenerated stub
    }

    /**
     * 获取站点列表
     * @return array
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\DbException
     * @throws \think\db\exception\ModelNotFoundException
     * @author PENGKING
     * @since 2020/11/15
     */
    public function getItemList()
    {
        $list = $this->model->where("status", "=", 1)
            ->where("mark", "=", 1)
            ->order("sort", "asc")
            ->select()
            ->toArray();
        return message("操作成功", true, $list);
    }

}