<?php


namespace app\admin\service;

use app\admin\model\LayoutDesc;

/**
 * 布局描述-服务类
 * @author PENGKING
 * @since 2020/11/15
 * Class LayoutDescService
 * @package app\admin\service
 */
class LayoutDescService extends BaseService
{
    /**
     * 构造函数
     * @author PENGKING
     * @since 2020/11/15
     * LayoutDescService constructor.
     */
    public function __construct()
    {
        $this->model = new LayoutDesc();
    }

    /**
     * 获取布局描述列表
     * @return array
     * @since 2021/12/16
     * @author PENGKING
     */
    public function getList()
    {
        // 参数
        $param = request()->param();

        // 查询条件
        $map = [];

        // 布局描述
        $locDesc = getter($param, "loc_desc");
        if ($locDesc) {
            $map[] = ["loc_desc", 'like', "%{$locDesc}%"];
        }
        return parent::getList($map, "id asc"); // TODO: Change the autogenerated stub
    }

    /**
     * 获取布局描述列表
     * @return array
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\DbException
     * @throws \think\db\exception\ModelNotFoundException
     * @author PENGKING
     * @since 2021/10/14
     */
    public function getLayoutDescList()
    {
        $list = $this->model
            ->where("mark", "=", 1)
            ->order("sort", "asc")
            ->select()
            ->toArray();
        return message("操作成功", true, $list);
    }

}