<?php


namespace app\admin\service;

use app\admin\model\Level;

/**
 * 职级管理-服务类
 * @author PENGKING
 * @since 2020/11/14
 * Class LevelService
 * @package app\admin\service
 */
class LevelService extends BaseService
{
    /**
     * 构造函数
     * @author PENGKING
     * @since 2020/11/14
     * LevelService constructor.
     */
    public function __construct()
    {
        $this->model = new Level();
    }

    /**
     * 获取数据
     * @return array
     * @since 2021/9/23
     * @author PENGKING
     */
    public function getList()
    {
        return parent::getList([], "id sort"); // TODO: Change the autogenerated stub
    }

    /**
     * 获取职级列表
     * @return array
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\DbException
     * @throws \think\db\exception\ModelNotFoundException
     * @author PENGKING
     * @since 2020/11/14
     */
    public function getLevelList()
    {
        $list = $this->model->where([
            ['status', '=', 1],
            ['mark', '=', 1],
        ])->order("sort", "asc")
            ->select()
            ->toArray();
        return message("操作成功", true, $list);
    }

}