<?php 


namespace app\admin\service;


use app\admin\model\OauthClient;

/**
 * 开放平台授权管理-服务类
 * @author PENGKING
 * @since: 2022/07/14
 * Class OauthClientService
 * @package app\admin\service
 */
class OauthClientService extends BaseService
{
    /**
     * 构造函数
     * LevelService constructor.
     */
    public function __construct()
    {
        $this->model = new OauthClient();
    }
	
	/**
     * 获取数据列表
     * @return array
     * @since 2022/07/14
     * @author PENGKING
     */
    public function getList()
    {
        $param = request()->param();

        // 查询条件
        $map = [];
		

        return parent::getList($map); // TODO: Change the autogenerated stub
    }


                            
        /**
        * 获取数据列表
        * @return array
        * @since 2022/07/14        * @author PENGKING        */
        public function getListSelect()
        {
            return parent::getListSelect();
        }

}