<?php 


namespace app\admin\service;


use app\admin\model\OpenLog202203;

/**
 * 系统行为日志管理-服务类
 * @author PENGKING
 * @since: 2022/03/29
 * Class OpenLog202203Service
 * @package app\admin\service
 */
class OpenLog202203Service extends BaseService
{
    /**
     * 构造函数
     * LevelService constructor.
     */
    public function __construct()
    {
        $this->model = new OpenLog202203();
    }
	
	/**
     * 获取数据列表
     * @return array
     * @since 2022/03/29
     * @author PENGKING
     */
    public function getList()
    {
        $param = request()->param();

        // 查询条件
        $map = [];
		
	
	    // 有效标识
        $mark = isset($param['mark']) ? (int)$param['mark'] : 0;
        if ($mark) {
            $map[] = ['mark', '=', $mark];
        }
	
        return parent::getList($map); // TODO: Change the autogenerated stub
    }


                                                
}