<?php


namespace app\admin\service;

use app\admin\model\Dept;

/**
 * 组织机构-服务类
 * @author PENGKING
 * @since 2021/7/5
 * Class OrganizationService
 * @package app\admin\service
 */
class OrganizationService extends BaseService
{
    /**
     * 构造函数
     * @author PENGKING
     * @since 2021/7/5
     * OrganizationService constructor.
     */
    public function __construct()
    {
        $this->model = new Dept();
    }

    /**
     * 获取机构列表
     * @return array
     * @since 2021/7/5
     * @author PENGKING
     */
    public function getList()
    {
        return parent::getList([], "sort asc"); // TODO: Change the autogenerated stub
    }

}