<?php


namespace app\admin\service;

use app\admin\model\Position;

/**
 * 岗位管理-服务类
 * @author PENGKING
 * @since 2020/11/14
 * Class PositionService
 * @package app\admin\service
 */
class PositionService extends BaseService
{
    /**
     * 构造函数
     * @author PENGKING
     * @since 2020/11/14
     * PositionService constructor.
     */
    public function __construct()
    {
        $this->model = new Position();
    }

    /**
     * 获取数据列表
     * @return array
     * @since 2021/9/23
     * @author PENGKING
     */
    public function getList()
    {
        return parent::getList([], "id asc"); // TODO: Change the autogenerated stub
    }

    /**
     * 获取岗位列表
     * @return array
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\DbException
     * @throws \think\db\exception\ModelNotFoundException
     * @author PENGKING
     * @since 2020/11/14
     */
    public function getPositionList()
    {
        $list = $this->model->where([
            ['status', '=', 1],
            ['mark', '=', 1],
        ])->order("sort", "asc")
            ->select()
            ->toArray();
        return message("操作成功", true, $list);
    }

}