<?php 


namespace app\admin\service;


use app\admin\model\Test6;

/**
 * 关联5管理-服务类
 * @author PENGKING
 * @since: 2022/07/27
 * Class Test6Service
 * @package app\admin\service
 */
class Test6Service extends BaseService
{
    /**
     * 构造函数
     * LevelService constructor.
     */
    public function __construct()
    {
        $this->model = new Test6();
    }
	
	/**
     * 获取数据列表
     * @return array
     * @since 2022/07/27
     * @author PENGKING
     */
    public function getList()
    {
        $param = request()->param();

        // 查询条件
        $map = [];
		
	
	    // 姓名
        $name = isset($param['name']) ? trim($param['name']) : '';
        if ($name) {
            $map[] = ['name', 'like', "%{$name}%"];
        }
	
        return parent::getList($map); // TODO: Change the autogenerated stub
    }


                                            
        /**
        * 获取数据列表
        * @return array
        * @since 2022/07/27        * @author PENGKING        */
        public function getListSelect()
        {
            return parent::getListSelect();
        }

}