<?php 


namespace app\admin\service;


use app\admin\model\Test2;

/**
 * Test2管理-服务类
 * @author PENGKING
 * @since: 2022/07/22
 * Class Test2Service
 * @package app\admin\service
 */
class Test2Service extends BaseService
{
    /**
     * 构造函数
     * LevelService constructor.
     */
    public function __construct()
    {
        $this->model = new Test2();
    }
	
	/**
     * 获取数据列表
     * @return array
     * @since 2022/07/22
     * @author PENGKING
     */
    public function getList()
    {
        $param = request()->param();

        // 查询条件
        $map = [];
		
	
	    // 姓名
        $name = isset($param['name']) ? trim($param['name']) : '';
        if ($name) {
            $map[] = ['name', 'like', "%{$name}%"];
        }
	
        return parent::getList($map); // TODO: Change the autogenerated stub
    }

	/**
     * 添加或编辑
     * @return array
     * @since 2022/07/22
     * @author PENGKING
     */
    public function edit()
    {
        // 参数
        $data = request()->param();
	                                                                                                                    
		// 图片处理
        $images = getter($data, 'images');
        if (!empty($images)) {
            if (strpos($images, "temp") !== false) {
                $data['images'] = save_image($images, 'test2');
            } else {
                $data['images'] = str_replace(IMG_URL, "", $images);
            }
        }
                                                
        return parent::edit($data); // TODO: Change the autogenerated stub
    }

                                                    
        /**
        * 获取数据列表
        * @return array
        * @since 2022/07/22        * @author PENGKING        */
        public function getListSelect()
        {
            return parent::getListSelect();
        }

}