<?php 


namespace app\admin\service;


use app\admin\model\TqUser;

/**
 * 腾青用户管理-服务类
 * @author PENGKING
 * @since: 2022/05/31
 * Class TqUserService
 * @package app\admin\service
 */
class TqUserService extends BaseService
{
    /**
     * 构造函数
     * LevelService constructor.
     */
    public function __construct()
    {
        $this->model = new TqUser();
    }
	
	/**
     * 获取数据列表
     * @return array
     * @since 2022/05/31
     * @author PENGKING
     */
    public function getList()
    {
        $param = request()->param();

        // 查询条件
        $map = [];
		
	
	    // 真实姓名
        $name = isset($param['name']) ? trim($param['name']) : '';
        if ($name) {
            $map[] = ['name', 'like', "%{$name}%"];
        }
		
	    // 实名认证
        $idcard_auth = isset($param['idcard_auth']) ? (int)$param['idcard_auth'] : 0;
        if ($idcard_auth) {
            $map[] = ['idcard_auth', '=', $idcard_auth];
        }
		
	    // 来源
        $source = isset($param['source']) ? (int)$param['source'] : 0;
        if ($source) {
            $map[] = ['source', '=', $source];
        }
		
	    // 状态
        $status = isset($param['status']) ? (int)$param['status'] : 0;
        if ($status) {
            $map[] = ['status', '=', $status];
        }
		
	    // 有效标识
        $mark = isset($param['mark']) ? (int)$param['mark'] : 0;
        if ($mark) {
            $map[] = ['mark', '=', $mark];
        }
	
        return parent::getList($map); // TODO: Change the autogenerated stub
    }

	/**
     * 添加或编辑
     * @return array
     * @since 2022/05/31
     * @author PENGKING
     */
    public function edit()
    {
        // 参数
        $data = request()->param();
	                                                                                                                                
		// 用户头像处理
        $avatar = getter($data, 'avatar');
        if (!empty($avatar)) {
            if (strpos($avatar, "temp") !== false) {
                $data['avatar'] = save_image($avatar, 'tquser');
            } else {
                $data['avatar'] = str_replace(IMG_URL, "", $avatar);
            }
        }
                                                                                                                                                                                                                                                                        
        return parent::edit($data); // TODO: Change the autogenerated stub
    }

                                                        		                                                                        
        /**
        * 获取数据列表
        * @return array
        * @since 2022/05/31        * @author PENGKING        */
        public function getListSelect()
        {
            return parent::getListSelect();
        }

}