<?php namespace app\admin\service;


use app\admin\model\UserDynamic;

/**
 * 用户发布动态管理-服务类
 * @author PENGKING
 * @since: 2022/10/08
 * Class UserDynamicService
 * @package app\admin\service
 */
class UserDynamicService extends BaseService
{
    /**
     * 构造函数
     * LevelService constructor.
     */
    public function __construct()
    {
        $this->model = new UserDynamic();
    }

    /**
     * 获取数据列表
     * @return array
     * @since 2022/10/08
     * @author PENGKING
     */
    public function getList()
    {
        $param = request()->param();

        // 查询条件
        $map = [];


        // 动态标题
        $title = isset($param['title']) ? trim($param['title']) : '';
        if ($title) {
            $map[] = ['title', 'like', "%{$title}%"];
        }

        // 状态
        $status = isset($param['status']) ? (int)$param['status'] : 0;
        if ($status) {
            $map[] = ['status', '=', $status];
        }

        return parent::getList($map); // TODO: Change the autogenerated stub
    }


    /**
     * 获取数据列表
     * @return array
     * @since 2022/10/08* @author PENGKING
     */
    public function getListSelect()
    {
        return parent::getListSelect();
    }

}