<?php namespace app\admin\service;


use app\admin\model\UserDynamicComment;

/**
* 用户动态评论管理-服务类
* @author PENGKING
* @since: 2022/10/08
* Class UserDynamicCommentService
* @package app\admin\service
*/
class UserDynamicCommentService extends BaseService
{
/**
* 构造函数
* LevelService constructor.
*/
public function __construct()
{
$this->model = new UserDynamicComment();
}

/**
* 获取数据列表
* @return array
* @since 2022/10/08
* @author PENGKING
*/
public function getList()
{
$param = request()->param();

// 查询条件
$map = [];


return parent::getList($map); // TODO: Change the autogenerated stub
}


                                                                                                                
/**
* 获取数据列表
* @return array
* @since 2022/10/08* @author PENGKING*/
public function getListSelect()
{
return parent::getListSelect();
}

}