<?php 


namespace app\admin\service;


use app\admin\model\Voteconfig;

/**
 * 投票设置管理-服务类
 * @author PENGKING
 * @since: 2022/07/25
 * Class VoteconfigService
 * @package app\admin\service
 */
class VoteconfigService extends BaseService
{
    /**
     * 构造函数
     * LevelService constructor.
     */
    public function __construct()
    {
        $this->model = new Voteconfig();
    }
	
	/**
     * 获取数据列表
     * @return array
     * @since 2022/07/25
     * @author PENGKING
     */
    public function getList()
    {
        $param = request()->param();

        // 查询条件
        $map = [];
		
	
	    // 投票标题
        $title = isset($param['title']) ? trim($param['title']) : '';
        if ($title) {
            $map[] = ['title', 'like', "%{$title}%"];
        }
		
	    // 投票状态
        $status = isset($param['status']) ? (int)$param['status'] : 0;
        if ($status) {
            $map[] = ['status', '=', $status];
        }
	
        return parent::getList($map); // TODO: Change the autogenerated stub
    }

	/**
     * 添加或编辑
     * @return array
     * @since 2022/07/25
     * @author PENGKING
     */
    public function edit()
    {
        // 参数
        $data = request()->param();
	                                                                                                                                            
		// 封面图片处理
        $images = getter($data, 'images');
        if (!empty($images)) {
            if (strpos($images, "temp") !== false) {
                $data['images'] = save_image($images, 'voteconfig');
            } else {
                $data['images'] = str_replace(IMG_URL, "", $images);
            }
        }
                                                
        return parent::edit($data); // TODO: Change the autogenerated stub
    }

                                                    		        
        /**
        * 获取数据列表
        * @return array
        * @since 2022/07/25        * @author PENGKING        */
        public function getListSelect()
        {
            return parent::getListSelect();
        }

}