<?php


namespace app\admin\service;

use app\admin\model\WebProject;

/**
 * 网站专业-服务类
 * @author PENGKING
 * @since 2021/7/6
 * Class WebsiteProjectService
 * @package app\admin\service
 */
class WebProjectService extends BaseService
{
    /**
     * 构造函数
     * @author PENGKING
     * @since 2021/7/6
     * WebsiteProjectService constructor.
     */
    public function __construct()
    {
        $this->model = new WebProject();
    }

    /**
     * 添加或编辑
     * @return array
     * @since 2021/7/6
     * @author PENGKING
     */
    public function edit()
    {
        // 参数
        $data = request()->param();
        // 封面处理
        $cover = trim($data['cover']);
        if (strpos($cover, "temp")) {
            $data['cover'] = save_image($cover, 'project');
        } else {
            $data['cover'] = str_replace(IMG_URL, "", $data['cover']);
        }
        // 文章图集
        $imgStr = [];
        $imgsList = isset($data['imgs']) ? $data['imgs'] : [];
        if ($imgsList) {
            foreach ($imgsList as $val) {
                if (strpos($val, "temp")) {
                    //新上传图片
                    $imgStr[] = save_image($val, 'project');
                } else {
                    //过滤已上传图片
                    $imgStr[] = str_replace(IMG_URL, "", $val);
                }
            }
        }
        $data['imgs'] = serialize($imgStr);
        //内容处理
        save_image_content($data['content'], $data['title'], "article");
        return parent::edit($data); // TODO: Change the autogenerated stub
    }

}