<?php 


namespace app\admin\service;


use app\admin\model\WechatConfig;

/**
 * 微信配置管理-服务类
 * @author PENGKING
 * @since: 2022/06/17
 * Class WechatConfigService
 * @package app\admin\service
 */
class WechatConfigService extends BaseService
{
    /**
     * 构造函数
     * LevelService constructor.
     */
    public function __construct()
    {
        $this->model = new WechatConfig();
    }
	
	/**
     * 获取数据列表
     * @return array
     * @since 2022/06/17
     * @author PENGKING
     */
    public function getList()
    {
        $param = request()->param();

        // 查询条件
        $map = [];
		
	
	    // 名称
        $name = isset($param['name']) ? trim($param['name']) : '';
        if ($name) {
            $map[] = ['name', 'like', "%{$name}%"];
        }
		
	    // 有效标识
        $make = isset($param['make']) ? (int)$param['make'] : 0;
        if ($make) {
            $map[] = ['make', '=', $make];
        }
	
        return parent::getList($map); // TODO: Change the autogenerated stub
    }


                        
        /**
        * 获取数据列表
        * @return array
        * @since 2022/06/17        * @author PENGKING        */
        public function getListSelect()
        {
            return parent::getListSelect();
        }

}