


namespace app\admin\controller;


use app\admin\service\<?php echo $moduleName?>Service;

/**
 * <?php echo $moduleTitle?>管理-控制器
 * @author <?php echo $author?>

 * @since: <?php echo $since?>

 * Class <?php echo $moduleName?>

 * @package app\admin\controller
 */
class <?php echo $moduleName?> extends Backend
{
    /**
     * 初始化方法
     * @author <?php echo $author?>

     * @since: <?php echo $since?>

     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new <?php echo $moduleName?>Service();
    }
	
<?php if ($columnList) {?>
<?php foreach ($columnList as $val) { ?>
    <?php if (isset($val['columnSwitch']) && $val['columnSwitch']) {?>
    <?php if ($val['columnName'] != "status") {?>

	/**
	 * 设置<?php echo $val['columnComment']?>

	 * @return mixed
	 * @since <?php echo $since?>

	 * @author <?php echo $author?>
	 
	 */
	public function <?php echo $val['columnSwitchName']?>()
	{
		if (IS_POST) {
			$result = $this->service-><?php echo $val['columnSwitchName']?>();
			return $result;
		}
	}
    <?php } ?>
	<?php } ?>
<?php } ?>
<?php } ?>

        /**
        * 获取数据列表
        * @return array
        * @since <?php echo $since?>

        * @author <?php echo $author?>


        */
        public function getListSelect()
        {
            $result = $this->service->getListSelect();
            return $result;
        }




}